language: android
dist: trusty
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-30.0.0
    - android-16
    - add-on
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-25
    - sys-img-armeabi-v7a-google_apis-google-25
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    - intel-android-extra-license.+

before_install:
  - yes | sdkmanager "platforms;android-25"
  - yes | sdkmanager "platforms;android-26"

install: true

addons:
  apt:
    packages:
      - python3.5

before_script:
  # Download and install gcloud cli to run firebase test commands
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-308.0.0-linux-x86_64.tar.gz
  - tar zxf google-cloud-sdk-308.0.0-linux-x86_64.tar.gz
  - echo n | ./google-cloud-sdk/install.sh
  - echo y | ./google-cloud-sdk/bin/gcloud components update
  - echo y | ./google-cloud-sdk/bin/gcloud components install beta
  - wget https://firebasestorage.googleapis.com/v0/b/go4lunch-e53cf.appspot.com/o/go4lunch-e53cf-51901af29b9f.json?alt=media&token=80caf8f7-e9a8-4a5f-ab86-7150602d9b4f

script:
  - chmod +x gradlew
  - ./gradlew assembleDebug
  - ./gradlew assembleDebugAndroidTest
  - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file go4lunch-e53cf-51901af29b9f.json\?alt\=media&token=80caf8f7-e9a8-4a5f-ab86-7150602d9b4f
  - ./google-cloud-sdk/bin/gcloud config set project go4lunch-e53cf
  - ./google-cloud-sdk/bin/gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Nexus6,version=25